#------------------------------------------------------------------
# This pipeline automates the release process for the Feed extension
# It sets the build title and triggers release definition in each stage with the specified version.
#------------------------------------------------------------------
# NOTE:
# To use this one of the PipelinesNNN Library needs to be linked to this pipeline (through UI).
# This uses variables from the library.
#------------------------------------------------------------------
# Parameters:
# - PoolName: The agent pool to use for the jobs. Default is "Azure Pipelines".
# - ReleaseVersion: The version of the release to be used.
#------------------------------------------------------------------
parameters:
  - name: "PoolName"
    type: string
    default: "Azure Pipelines"
    values:
      - "Azure Pipelines"
      - "Omnia Agents"

  - name: ReleaseVersion
    type: string
    default: ""

trigger: none

resources:
  repositories:
    - repository: OmniaPipelines
      type: github
      name: "omniaintranet/OmniaPipelines"
      ref: $(Build.SourceBranch)
      endpoint: "omniaintranet"

stages:
  - stage: SetTitleOnBuild
    dependsOn: []
    displayName: "Set Title"
    jobs:
      - job: SetTitleOnBuildJob
        pool:
          name: ${{ parameters.PoolName }}
        steps:
          - template: ../../templates/generic-set-build-version-number-on-build.yml
            parameters:
              ReleaseVersion: "${{ parameters.ReleaseVersion }}"

  #------------------------------------------------------------------
  # Add stages for each cloud that you want to automatically release to.
  #------------------------------------------------------------------
  - stage: ReleaseUAT
    dependsOn: []
    displayName: "UAT"
    jobs:
      - job: ReleaseUATJob
        pool:
          name: ${{ parameters.PoolName }}
        displayName: "Release to UAT"
        steps:
          - checkout: OmniaPipelines
          - template: ../../templates/generic-trigger-extension-release-definition.yml
            parameters:
              DefinitionId: 419              # Feed UAT Definition ID
              ReleaseVersion: ${{ parameters.ReleaseVersion }}
              PoolName: ${{ parameters.PoolName }}
              PipelineName: "Feed - Release" # only for display purposes
