parameters:
  - name: BuildNumber
    type: string
    default: ""

  - name: MainVersion
    type: string
    default: ""

  - name: Tag
    type: string
    default: "dev" # should be latest in prod branch
    displayName: "Tag"

  - name: "PoolName"
    type: string
    default: "Azure Pipelines"
    values:
      - "Azure Pipelines"
      - "Omnia Agents"

  - name: RepositoryName
    type: string
    default: ""

  - name: ExtensionId
    type: string
    default: ""

  # EnsureVersion -> Push_TestCloud_ProdIntent  -> Push_ProdCloud_ProdIntent
  #                                             -> Push_TestCloud_DevIntent
stages:
  - stage: EnsureVersion
    dependsOn: []
    displayName: "Ensure Version"
    jobs:
      - job: EnsureVersionJob
        pool:
          name: ${{ parameters.PoolName }}
        steps:
          - checkout: OmniaPipelines

          - template: ../templates/generic-ensure-version-as-variable.yml
            parameters:
              BuildNumber: ${{ parameters.BuildNumber }}
              Tag: ${{ parameters.Tag }}
              MainVersion: ${{ parameters.MainVersion }}

          - template: ../templates/generic-set-buildnumber-on-build.yml
            parameters:
              Version: "$(Version)"
              BuildVersion: ${{ parameters.BuildNumber }}

          - script: |
              echo "Setting version: $(Version)"
              echo "##vso[build.addbuildtag]$(Version)"
              echo "##vso[task.setvariable variable=Version;isOutput=true]$(Version)"
            name: EnsureVersionTask
            displayName: "Setting version variable and tag"

  # ------------------------------------------------------------------
  # STAGE: Push Omnia Extensions to Custom Cloud - Prod intent
  # ------------------------------------------------------------------
  - stage: Push_ProdCloud_ProdIntent
    dependsOn: [EnsureVersion, Push_TestCloud_ProdIntent]
    displayName: "Push Prod Cloud (Prod intent)"
    jobs:
      - job: Push_ProdCloud_ProdIntentJob
        pool:
          name: ${{ parameters.PoolName }}
        variables:
          Version: $[ stageDependencies.EnsureVersion.EnsureVersionJob.outputs['EnsureVersionTask.Version'] ]
        displayName: "Push Prod Cloud (Prod intent)"
        steps:
          - checkout: OmniaPipelines
          - checkout: ${{ parameters.RepositoryName }}

          - template: ../templates/generic-rename-source-folders.yml
            parameters:
              RepositoryName: ${{ parameters.RepositoryName }}

          # -----------------------------------------------------------------
          # init dotnet and npm, and omnia cli
          # Download and unzip drop
          # -----------------------------------------------------------------
          - template: ../templates/generic-init-dotnet-omnia-npm.yml
            parameters:
              dotnetVersion: "9.0.101"
              Tag: ${{ parameters.Tag }}

          - template: ../templates/generic-download-and-unpack-drop.yml
            parameters:
              DropName: $(dropName)
              WorkspacePath: "$(Pipeline.Workspace)"
              StripComponents: 4

          # -----------------------------------------------------------------
          # Build Omnia - Docker image and publish to AZ Container Registry
          # -----------------------------------------------------------------
          - template: ../templates/generic-extension-build-to-repository-and-cloud.yml
            parameters:
              Version: "$(Version)"
              CloudClientId: "$(ProdCloudClientId)"
              CloudClientSecret: "$(ProdCloudClientSecret)"
              ExtensionId: ${{ parameters.ExtensionId }}
              Intent: "prod"
              Environment: "prod"
              ExtensionJsonPath: "$(Build.ArtifactStagingDirectory)/extension.json"
              ApiAppBaseUrl: "$(apiappbase)"
              CloudApiAppId: "$(cloudapiappid)"
              CloudApiUrl: "$(cloudapiurl)"
              CliAppId: "$(cliappid)"
              ExtensionName: ${{ parameters.RepositoryName }}
